### PR TITLE
Water Year 2016 update

### PR DESCRIPTION
**Pull request by andybell**
Updates repository to include data from the 2016 water year.

Includes:
- daily spatial cimis from 10/01/2015 - 9/30/2016
- aggregates to cimis to monthly, wy rasters (note: 2016 was leap year so yearly raster has 366 bands)
- daily weather station for 2016 water year

TODOs:
- [x] lodi_west station does not have any data. Maybe went offline?
- [x] hourly weather stations max api thresholds #5
- [x] update repository readme

### CODE REVIEW

**Comment by andybell** [comment]
Lodi West (station ID = 166) went offline on 3/20/2015. Removing from 2016 water year folders.

**Comment by nickrsan** [comment]
At first glance, this looks good to me - anything specific you want me to take a look at?

**Comment by andybell** [comment]
@nickrsan any good ideas about how to deal with the API limit for the hourly weather data?

**Comment by jessejanko** [comment]
Looks great, thanks @andybell

**Pull request merged**
